# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Atif Farooqui
title: Enthusiastic Job Applicant
email: digitalprague@gmail.com
phone: 777-988-681
website: www.studentprague.tk

darkmode: false

# Social links
twitter_username: studentprague
github_username:  dailyblog99


# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: resume/image/IMG_5602.png
about_content: | # this will include new lines to allow paragraphs
  Having lived in different cities, countries and cultures over the years, it has afforded me a unique perspective towards creativity and towards life. While the internet is busy dirupting all walks of life it is important for us to create a raft of knowledge, one which will take us to safety.



# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  While I am not busy learning new things I like to read and watch movies and write stories that excite me. From all the new things that one can learn, I find *languages* really exciting. Here are some of the languages that I try to speak:
 - English
 - Hindi
 - Czech
 - Italian
   - A1
 - German
   - Just Began
  
  Other than these things I enjoy spending time with my family and our dog. 
# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jrkyll-image-size

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
