# Site
repository: bongjovi/bongjovi.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Atif Farooqui
title: In search of new opportunities in Prague
address: K Trninam, Repy, Prague
email: atsayfar@gmail.com
phone: 777-988-681

darkmode: false

# Social links



# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: image/favico.png
about_content: | # this will include new lines to allow paragraphs
  >  “Not all those who wander are lost."
      -J.R.R Tolkien
  
  Ten cities, three countries and two continents later one truly begins to comprehend the benefits of traveling. 
  
  # Hi ! I am Atif.
  
   I am based in Prague and in search of an enthusiastic team to join. During my research for top places to work in Prague your firm's name came up. While I understand that there are many exciting positions on offer, I am interested in Account Management.
   Along with a rich experience in FMCG I bring along some of these skill sets

   <mark>Market Penetration</mark>
   <mark>Account Acquisition</mark>,
   <mark>Product Strategy</mark>,
   <mark>Trade Communication</mark>,
   <mark>Sales Estimation</mark>,<mark>Budgeting</mark>,<mark>Client Servicing</mark>
  


# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  While I am not busy watching films I try learning new languages. Here are some of the languages that I try to speak:
  - English   - Advanced
  - Hindi     - Advanced
  - Czech     - Upper Intermediate
  - Italian   - Beginner 
  
    
  
  Other than these things I enjoy spending time with my family and our dog.
  
  <em>Resume Theme Credit : [Sproogen](https://github.com/sproogen/modern-resume-theme)</em>
# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jrkyll-image-size

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
